from pathlib import Path
import json,collections,datetime,hashlib,csv
P=Path(__file__).parent;B=P.parent.parent
S=json.loads((P/'read-context-summary.json').read_text());R=json.loads((P/'representative-reads.json').read_text());M=json.loads((P/'candidate-position-mapping.json').read_text());C=json.loads((P/'ordinary-reference-search/control-and-cap-summary.json').read_text());T=json.loads((P.parent/'independent-count-audit/sensitivity-and-exact-discordances.json').read_text());Q=json.loads((P/'ordinary-reference-search/scored-results.json').read_text());D=json.loads((P/'specific-context-metrics.json').read_text())
# Improve an ambiguous field label without changing any recorded value.
for k,v in D.items():
 if k!='PABPC1_phase' and 'names'in v:v['all_qualifying_name_units_including_conflicts']=v.pop('names')
(P/'specific-context-metrics.json').write_text(json.dumps(D,indent=2)+'\n')
texts={
'chr2:189043211':('aligned_start_sensitive; biological mechanism unresolved','All208 qualifying unexpected-A alignment observations (116 name units) are within5 bases of an aligned query end;190 are at stored query position0, and all208 at aligned query start. Clean filtering removes all116 A names but retains183 G names. All8 selected unexpected sequences best match ordinary COL5A2 transcripts at the same position (7 perfect,1 with another mismatch). This is an end-dependent observation, not proof of a paralog or of the cause of the end bias.'),
'chr3:195568834':('local_indel_placement_ambiguity_in_representatives; unresolved origin','All37 qualifying C-bearing alignment observations (27 names) have a nearby4bp insertion at boundary chr3:195568840 zero-based, within a G-rich run. In first-best nominated ordinary local alignments, the queried C falls within an insertion for7/8 selected sequences and at a nearby different position for1/8. These alternatives can score below a source-CIGAR model containing the unexpected allele (example278 versus283); they demonstrate placement ambiguity, not correction of all27 names or proof of biological origin. Clean C24/G0 has reduced depth, not resolution.'),
'chr5:443259':('repeat_and_local_gap_placement_ambiguity; capped_search; unresolved origin','The locus is in a GCG-rich repeat. All37 qualifying A-bearing alignment observations (22 names) have a21-base N operation at chr5:[443260,443281) zero-based. In8/8 selected sequences the queried A moves to the matching reference A at chr5:443280 one-based in first-best nominated ordinary local alignments (+21bases). Example ordinary score292 is below the source-CIGAR/unexpected-allele score310, so origin is not adjudicated. Several expected-C sequences are short/softclipped and have other repeat matches. Seed/window caps affect EXOC3 representatives; no uniqueness or exhaustive-best claim.'),
'chr5:80654917':('local_repeat_gap_placement_ambiguity_in_representatives; unresolved origin','The position overlaps MSH3 and DHFR in opposite orientations. Among189 qualifying G-bearing alignment observations (104 names),147 have a27-base N at chr5:[80654887,80654914);42 have the nearby1446-base splice instead. All8 selected sequences place the queried G at matching reference chr5:80654908 one-based (−9bases) in their first-best nominated ordinary alignment, including MSH3 or reverse-complement DHFR models. Source-CIGAR/unexpected-allele models can score higher (example290 versus259), so these are alternative gap placements, not a validated preferred origin or changed genotype.'),
'chr8:100705591':('partly_clean_filter_sensitive; same_position_mismatches_persist; unresolved','Unexpected G decreases from65 names to9 under clean filtering but is not eliminated. All8 selected unexpected sequences retain the queried mismatch at the same PABPC1 coordinate in their best nominated ordinary transcript alignment; expected representatives fit ordinary PABPC1. No cleaner different-locus origin was established in the nominated set. All65 G names also have C at the nearby604 site in the same qualifying alignment; these are shared support, not independent sample checks.'),
'chr8:100705604':('partly_clean_filter_sensitive; same_position_mismatches_persist; unresolved','Unexpected C decreases from78 names to31 under clean filtering but is not eliminated. All8 selected unexpected sequences retain the queried mismatch at the same PABPC1 coordinate in their best nominated ordinary transcript alignment.65 of78 C names overlap the591 G call in one qualifying alignment;13 C names lack a jointly callable591. No unique origin, biological cause or correction is established.'),
'chr3:10049469':('MAPQ60_only_filter_selection_effect; local_paralog_compatibility_not_origin_proof','Baseline DNA C713/T28 and RNA C72/T153 become DNA C230/T0 with RNA unchanged underMAPQ60. The2 selected DNA-T sequences (7 baseline names) each match161bp perfectly at FANCD2P2, with queried base at chr3:11871392 one-based, versus one mismatch to public FANCD2; changing the FANCD2 source-path allele toT also yields a perfect score. RNA-T representatives retain the T at FANCD2. The ordinary pseudogene match documents ambiguity, not proof that DNA-T reads originate from the pseudogene or that the locus is incompatible.'),
'chr3:195677778':('MAPQ60_only_filter_selection_effect; unresolved origin','Baseline DNA A1472/G725 and RNA A913/G357 become DNA A118/G0 with RNA unchanged underMAPQ60. Selected unexpected DNA/RNA sequences retain their G at the original SDHAP2/MUC20-OT1 position in the best nominated ordinary reference alignment; source-path G substitution improves the fit. The allele-selective removal of DNA evidence is demonstrated, but the gene of origin and cause of mapping-quality differences are unresolved.'),
'chr9:65737280':('MAPQ60_only_filter_selection_effect; unresolved origin','Baseline DNA G818/A225 and RNA G70/A22 become DNA G260/A0 with RNA unchanged underMAPQ60. Selected unexpected DNA/RNA sequences retain A at the original FOXD4L4 position in the best nominated ordinary reference alignment; a source-path A model fits better. This new flag is generated by filtering away DNA alternate support, not by a change in RNA counts. No specific paralog origin is established.')}
by=collections.defaultdict(dict)
for s in S['summaries']:by[f'{s["site"]["chrom"]}:{s["site"]["pos1"]}'][s['assay']]=s
mapped={r['query_id']:r for r in M['rows']};bestscore={}
for r in Q['results']:
 if r['query']['kind']!='patient_representative':continue
 qid=r['query']['query_id'];v=bestscore.setdefault(qid,{'ordinary':-1e9,'source_CIGAR_allele_comparator':-1e9})
 v['ordinary']=max([v['ordinary']]+[x['score']for x in r['top_alternatives']])
 v['source_CIGAR_allele_comparator']=max([v['source_CIGAR_allele_comparator']]+[x['score']for x in r['source_CIGAR_paths']])
find=[]
for site,assays in by.items():
 info=assays['RNA']['site'];chosen=[r for r in R if f'{r["site"]["chrom"]}:{r["site"]["pos1"]}'==site];sel=[]
 for assay,role in sorted({(r['assay'],r['role'])for r in chosen}):
  rr=[r for r in chosen if r['assay']==assay and r['role']==role];base=rr[0]['base'];names={(a['name'],a['RG'])for r in rr for a in r['represented_records']};all_detail=assays[assay]['allele_detail'][base]
  sel.append({'assay':assay,'role':role,'base':base,'selected_distinct_full_sequences_at_this_locus':len(rr),'represented_unambiguous_name_units':len(names),'total_baseline_unambiguous_name_units':all_detail['names'],'total_stored_sequence_families':all_detail['full_stored_sequence_families'],'selected_sequence_ids':[r['id']for r in rr]})
 mappings=[{'query_id':r['id'],'family_names':r['family_names'],'base':r['base'],'role':r['role'],'assay':r['assay'],'first_best_ordinary_base_placement':mapped[r['id']]['mapping'],'scores':bestscore[r['id']]}for r in chosen]
 find.append({'locus':site,'gene_symbols':info['gene_symbols'],'selection':info['selection'],'expected_from_DNA_dominant_mode':info['expected_base'],'unexpected':info['unexpected_base'],'mechanism_label':texts[site][0],'finding':texts[site][1],'baseline':{a:v['modes']['baseline']for a,v in assays.items()},'clean':{a:v['modes']['clean']for a,v in assays.items()},'representative_selection':sel,'representative_mappings_and_scores':mappings,'limits':'Representative sequences/families are not independent molecules. First-best nominated alignments and allele-substituted original-CIGAR models are hypotheses, not validated true read origins.'})
report={'completed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'complete_pending_parent_editorial_review','scope':'Read-quality/origin follow-up of6 primary discordances plus3 MAPQ60-only sites, unchanged prior triage design/v2','loci':find,'method':{'indexed_site_alignment_observations':S['records'],'note_observations':'Observations can repeat across the two adjacent PABPC1 sites; not a count of unique BAM alignments.','baseline_clean_counts_match_independent_all_site_counter':True,'representative_selection_rows':len(R),'distinct_sequences_across_all_selection_rows':len({r['sequence']for r in R}),'selection':'Per site, at most8 unexpected RNA+4 expected RNA+2 unexpected DNA distinct stored sequences; rank by descending name support then lexical sequence. Names deduplicated across selected sequences in coverage summaries.','search':{'genome':'Existing GRCh38 primary assembly,194contigs','transcripts':'GENCODE37,234485transcripts','exact_seed_length':19,'seed_placements':'disjoint19nt blocks plus terminal19mer, both orientations','seed_hit_cap_per_reference_type':1000,'windows_per_query_per_reference_type':500,'patient_windows_scored':C['patient_windows_scored'],'windows_scored_with_controls':C['all_windows_scored_including_controls'],'caps':C['capped_seed_count'],'window_cap_events':len(C['window_caps']),'cap_scope':'Patient seed/window caps affect EXOC3 representatives; repeat control also capped. No exhaustive-search or unique-origin claim.'},'controls':'6 manual CIGAR position tests; baseline/clean count equality atall9 loci;7 ordinary-parent/edit/splice expected-score/source-window controls; ambiguous repeat control; root670 exported affine scores+7 scalar controls all match independent recurrence.'},'PABPC1_shared_support':D['PABPC1_phase'],'limits':['No identity probability, contamination fraction, clinical diagnosis or treatment inference.','RNA fractions and clean/MAPQ filters do not by themselves establish source, biology or resolution.','Selected sequences are a bounded subset; omissions and selection denominators are explicit.','Search excludes unrepresented alternate haplotypes and arbitrary unannotated splicing;19nt seed nomination may miss gapped alternatives.','One best traceback is reported; repeat-equivalent placements are not exhaustively enumerated.','Original-CIGAR path/allele models can outscore ordinary references; their structural form follows the original alignment and is not independent proof of origin.','No new full alignment/download/upload or full patient BAM scan.']}
(P/'findings.json').write_text(json.dumps(report,indent=2)+'\n')
with(P/'per-locus-findings.tsv').open('w')as f:
 w=csv.writer(f,delimiter='\t',lineterminator='\n');w.writerow(['locus','genes','selection','expected','unexpected','label','finding'])
 for r in find:w.writerow([r['locus'],r['gene_symbols'],r['selection'],r['expected_from_DNA_dominant_mode'],r['unexpected'],r['mechanism_label'],r['finding']])
print('wrote',len(find),'locus findings')
