#!/usr/bin/env python3
import datetime,hashlib,json,pathlib,shutil
ws=pathlib.Path(__file__).resolve().parent;base=pathlib.Path('/Users/burhanazeem/.local/share/codex/caris-analysis/oct4-fusion-read-audit');a=json.load(open(ws/'independent-warning-output-audit.json'));assert a['status']=='passed' and a['reason_sum']==a['expected_warning']==103932
note='''\nVerified diagnostic addendum — 5 October 2026\nThis supersedes the earlier pending warning-counter status above. A separate CSV/field comparison verified that all28 accepted calls are byte-identical between the stock and counter-only rerun. Both discarded files contain825,436 rows:825,433 have identical fields; the only3 differences reorder equal-distance gene1 labels (FAM95B1/BX664727.3 in two rows and OOSP4A/AP000790.1 in one). The same labels and multiplicities remain. Breakpoints, read counts, filters, sequences, read identifiers and all other fields are unchanged. Thus the discarded files are semantically equivalent for these calls, but are NOT byte-identical. The original frozen call files were not modified.\n\nIndependent log parsing reproduces103,932 =61,161 rejected paired alignment groups of unexpected size +5,303 paired groups with unresolved split/supplementary overlap +37,468 individual supplementary records clipped at the wrong end. The first two are alignment-group counts; the last is a record count. One biological fragment may contribute more than once across hits/stages. Do not turn this sum into unique reads, molecules, a percentage of input lost or a sensitivity estimate. No fatal BAM-decoder error occurred; this warning is not evidence of that parse-corruption failure. It also does not prove that all rejected evidence was harmless. Subsampling counters describe cap-branch encounters/distinct fusion keys, not exact numbers of skipped original molecules or transcript abundance.\n\nThe counter rerun explains existing filters and preserved the reported findings; it does not rescue rejected evidence, validate tumor specificity, cure sparse-index sensitivity or exclude all fusions/deletions/exon-skipping. The compact D1/D8 difference and intragenic-deletion limitation remain. Reproducible details and exact3-row differences: independent-warning-output-audit.json and independent_warning_output_audit.py; source diagnostics/warning-analysis.json and patient logs.\n'''
p=ws/'findings.txt';s=p.read_text();marker='\nVerified diagnostic addendum — 5 October 2026\n';assert marker not in s;p.write_text(s+note);shutil.copy2(p,base/'findings.txt')
for fn in ['independent-warning-output-audit.json','independent_warning_output_audit.py','append_warning_addendum.py']:shutil.copy2(ws/fn,base/fn)
def stamp(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
pr=json.load(open(ws/'provenance.json'))
for i,record in enumerate(pr['files']):
 if record['path']==str(p):pr['files'][i]=stamp(p)
new=[ws/'independent-warning-output-audit.json',ws/'independent_warning_output_audit.py',ws/'append_warning_addendum.py']
for q in new:
 if not any(x['path']==str(q) for x in pr['files']):pr['files'].append(stamp(q))
pr['verified_warning_addendum_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();pr['verified_warning_addendum']='Accepted byte-identical; discarded field-equivalent except3 equal-distance gene1 ordering changes;103932mixed-unit rejection counter independently reproduced; no filtering-sensitivity assurance.'
(ws/'provenance.json').write_text(json.dumps(pr,indent=2)+'\n');shutil.copy2(ws/'provenance.json',base/'provenance.json')
assert (ws/'findings.txt').read_bytes()==(base/'findings.txt').read_bytes();assert (ws/'provenance.json').read_bytes()==(base/'provenance.json').read_bytes()
print(json.dumps({'status':'final','findings_sha256':stamp(p)['sha256'],'mirror_identical':True,'provenance_mirror_identical':True,'calls_not_modified':True}))
