#!/usr/bin/env python3
import datetime,hashlib,json,pathlib,shutil,sys
ws=pathlib.Path(__file__).resolve().parent;base=pathlib.Path('/Users/burhanazeem/.local/share/codex/caris-analysis/oct4-fusion-read-audit');root=ws.parent
copyfiles=['candidate-reviewed.tsv','candidate-reviewed.json','review-status-counts.json','patient-inventory/inventory.json','supplemental-inventory/coordinate-formula-accepted-controls.json','patient/independent-recount.json','supplemental/independent-recount.json','patient-evidence/STAR-name-diagnostics.json','patient-evidence/shared-marker-groups.json','patient-evidence/normal-locus-neighbor-context.json']
for rel in copyfiles:
 p=base/rel;dest=ws/'evidence'/rel;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dest)
for fn in ['candidate-reviewed.tsv','candidate-reviewed.json']:shutil.copy2(base/fn,ws/fn)
for p in ws.glob('*.py'):shutil.copy2(p,base/p.name)
def stamp(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for c in iter(lambda:f.read(1048576),b''):h.update(c)
 return {'path':str(p),'bytes':p.stat().st_size,'sha256':h.hexdigest()}
ref=json.load(open(root/'input-reverification.json'));checks=[]
for x in ref['files']:
 s=pathlib.Path(x['path']).stat();checks.append({'path':x['path'],'same_size_as_pre_run_hash':s.st_size==x['size_bytes'],'same_mtime_as_pre_run_hash':s.st_mtime_ns==x['mtime_ns'],'pre_run_SHA256':x['sha256']})
p={'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'Research audit of28 accepted and26 predeclared selected discarded STAR/Arriba hypotheses. No clinical actionability, somatic status, protein expression or tumor-cell identity validated.','interpreter':sys.executable,'resident_evidence_directory':str(base),'source_fastq_integrity':checks,'source_reverification_file':stamp(root/'input-reverification.json'),'source_tsv_integrity':json.load(open(base/'patient-inventory/inventory.json'))['sources'],'source_run_completion':stamp(root/'patient-D8/completion-summary.json'),'original_selection_script':stamp(root/'inventory_candidates.py'),'adaptation':'Streaming storage; missing coverage dot parsed as null; selection predicates unchanged. Supplemental markers separately labelled: observed non-template insertion or joined genomic reference hypothesis.','supplemental_names':'For reference-reconstructed rows, STAR breakends of same genomic directions within25bp; NOT Arriba filtered read_identifiers. Final reviewed columns say source_named accordingly. Legacy supplemental compiler outputs retain caller_named field spelling with this explicit definition.','raw_pair_counts':{'primary':json.load(open(base/'patient/junction-read-audit.json'))['counts'],'supplemental':json.load(open(base/'supplemental/junction-read-audit.json'))['counts']},'checks':{'primary_separate_recount':json.load(open(base/'patient/independent-recount.json'))['status'],'supplemental_separate_recount':json.load(open(base/'supplemental/independent-recount.json'))['status'],'primary_reference_chunk_control':True,'supplemental_reference_chunk_control':True},'public_positive_control_limit':'Known BCR::ABL1 raw markers lose true-positive support under long/Q30 filters; zero exact count is not an exclusion.','files':[stamp(ws/f) for f in ['candidate-reviewed.tsv','candidate-reviewed.json','findings.txt','independent-DNA-spot-recount.json']]+[stamp(p) for p in ws.glob('*.py')],'full_resident_evidence_files':[stamp(base/r) for r in ['patient-inventory/all-triaged-candidates.jsonl.gz','patient-inventory/review-candidates.json','supplemental-inventory/review-candidates.json','patient/junction-read-audit.json','supplemental/junction-read-audit.json','patient-reference/reference-ambiguity.json','supplemental-reference/reference-ambiguity.json','patient/audit-selected.R1.fastq.gz','patient/audit-selected.R2.fastq.gz','supplemental/audit-selected.R1.fastq.gz','supplemental/audit-selected.R2.fastq.gz']],'originals_modified':False,'external_patient_data_submission_by_this_branch':False,'incremental_paid_cost_USD':0}
p['bounded_DNA_source_prior_full_verification']=next(v for v in json.load(open(ws.parents[2]/'oct1-analysis/resident-copies-verification.json'))['files'] if v['name']=='DNA_TN26-279853.bam')
p['bounded_DNA_expected_count_source']=stamp(ws/'independent-priority-review/bounded-DNA-details.json')
shutil.copy2(ws/'independent-DNA-spot-recount.json',base/'independent-DNA-spot-recount.json')
(ws/'provenance.json').write_text(json.dumps(p,indent=2)+'\n');shutil.copy2(ws/'provenance.json',base/'provenance.json');shutil.copy2(ws/'findings.txt',base/'findings.txt');print(json.dumps({'status':'packaged','files':len(p['files']),'FASTQ_size_mtime_unchanged':all(v['same_size_as_pre_run_hash'] and v['same_mtime_as_pre_run_hash'] for v in checks)}))
