from pathlib import Path
import json,datetime,hashlib,collections
B=Path(__file__).resolve().parent
A=json.loads((B/'independent-audit-data.json').read_text());P=json.loads((B/'independent-public-audit.json').read_text());S=json.loads((B/'screen-results.json').read_text())
common=[r for r in P['missense_public_context'] if any(float(f['frequency'])>=.01 for f in r.get('global_alt_frequencies',[]))]
rare=[r for r in P['missense_public_context'] if r not in common]
assert len(common)==16 and len(rare)==1 and rare[0]['gene']=='ALK' and rare[0]['protein']=='T1151M'
assert len(P['VCF_exact_comparison'])==54 and all(r['exact_matches'] for r in P['VCF_exact_comparison'])
assert '21 MANE Select plus NTRK3 APPRIS principal_1' in S['annotation_limit']
fg=[r for r in S['candidates'] if r['gene']=='FGFR1'][0]
assert fg['protein']!='S134D'
checks={'54_exact_source_VCF_matches':True,'22_selected_reference_proteins_match_GENCODE37':A['summary']['all_reference_proteins_match'],'all_52_coding_single_variant_translations_independently_checked':len([c for c in A['consequences'] if c['independent_status']=='single_edit_reference_translation'])==52,'21_MANE_plus_NTRK3_principal1_label_corrected':True,'FGFR1_misleading_missense_label_removed':True,'17_missense_public_exact_forward_alleles_verified':all(r['status']=='exact_catalog_match' for r in P['missense_public_context']),'16_missense_have_global_alt_frequency_at_least_one_percent':True,'ALK_T1151M_rare_population_allele_VUS_not_actionable':True}
text='''Independent audit of the 22-gene coding panel — PASS with corrections incorporated

No additional protein-altering candidate outside the supplied Caris VCF was identified by this bounded panel. All 54 events exactly match source genomic alleles. The 87,057 assessed CDS-plus-4-bp positions all meet 20-read depth, with minimum observed depth 146; this is read-depth coverage of selected transcripts, not validated clinical exclusion of all alterations.

Independent coordinate editing and a separate standard genetic-code implementation reproduce the 52 coding consequences; both other events are POLE near-CDS/intronic indels. All 22 selected reference proteins match the GENCODE37 protein FASTA. The annotation scope is now correctly stated as 21 MANE Select transcripts and NTRK3 APPRIS principal_1. ROS1 protein positions differ between selected GENCODE and Caris RefSeq isoforms; the genomic variants are identical, so this is not a biological discrepancy.

The screen contains 34 synonymous, 17 missense, one in-frame insertion, and two noncoding/CDS-flank events. Of the 18 protein-changing events, source Caris labels 17 Benign and ALK T1151M VUS. Independently queried public Ensembl/dbSNP records exactly match all 17 missense alleles after GRCh38 forward-coordinate/ref/alt verification. Sixteen have an observed alternate-allele frequency of at least 1% in a returned global reference population, independently supporting their low priority as tumor-specific treatment/vaccine targets. This is not proof of this patient's germline status or an independent clinical reclassification.

ALK T1151M is rs113994091, present rarely in the returned gnomADe ALL data at 0.00001642 (24 allele observations) and gnomADg ALL at 0.00004602 (7 observations). Caris calls it VUS, and public record-level metadata also reports uncertain significance. It remains an unresolved variant, not evidence for an ALK inhibitor. Its rare population presence means tumor-only sequencing cannot establish somatic status. The earlier primary-pipeline DNA/RNA recount is supporting evidence for the observed allele, not an independent second implementation or clinical validation.

FGFR1 chr8:38428395 G>GTCA: independent translation produces a one-aspartate expansion at the end of a poly-Asp tract, consistent with source D133dup. The earlier first-difference 'S134D' was misleading for an insertion and has been removed. Source Caris calls it Benign. Bounded exact haplotype counts demonstrate repeat-alignment sensitivity: with 12 reference flanks, RNA has 5 alt versus 3,646 reference paired names; with 30 flanks, it has 2,508 alt versus 223 reference paired names (241 other; 1 discordant). Longer windows capture equivalent insertion placements elsewhere inside the repeat that the short window misses. DNA also supports the 30-flank allele (819 alt, 228 reference, 32 other). These counts are representation- and window-dependent evidence, not unbiased VAF or independent molecule counts, and do not support an actionable FGFR activation claim.

POLE chr12:132661167 G>GA and GA>G: both are intronic/CDS-flank repeat events, not protein edits in the selected transcript. They already occur in Caris under filters sb;R8.1 and R8.1. Thirty-flank exact DNA counts are respectively 27 alt/224 reference/102 other and 53 alt/221 reference/76 other paired names. Shorter-flank counts differ. RNA windows were not adequately assessable (12-flank only six reference pairs; 30-flank none); this does not prove absence of expression or normal splicing. Neither event is promoted to pathogenic or treatment-relevant.

Audit filters for the bounded indel recount: primary, mapped, nonduplicate, QC-pass alignments; MAPQ and every included base quality at least 20; NH=1 where that tag exists; exact reference or alternate haplotypes spanning both reference flanks; exclude splice gaps crossing the window; combine paired read names and separate conflicting pairs. Repeat placement, overlapping reads, unmarked PCR duplicates, alternative transcript use and tumor-only material remain limitations. Saved compact CIGAR evidence and forward/reverse/endpoint counts are in independent-audit-data.json.

The broader scan is not a full-exome re-call, a copy-number/structural/fusion analysis, a complete splice analysis, a matched-normal somatic caller, or a clinically validated negative result. Low-allele-fraction alterations below the screening threshold, unselected isoforms, deeper intronic events and noncoding regulatory alterations remain outside scope. No treatment change follows from this panel alone.

Reproducibility: independent-audit.py and independent-audit-data.json preserve separate transcript translation and exact-haplotype checks. independent-public-audit.py/.json and independent-public-cache preserve generic public lookup URLs/responses, exact mappings and allele-specific frequencies. No patient identifier, read sequence or raw patient file was uploaded. Public clinical-significance metadata can combine alleles/conditions and was not used to reclassify an allele.
'''
(B/'audit.txt').write_text(text)
files=['screen.py','screen-results.json','target-annotation.json','independent-audit.py','independent-audit-data.json','independent-public-audit.py','independent-public-audit.json','audit.txt']
j={'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'result':'PASS with annotation/protein-label corrections incorporated','checks':checks,'public_missense_exact_matches':17,'public_missense_common_global_frequency_ge01':16,'remaining_missense':{'gene':'ALK','protein':'T1151M','rsid':'rs113994091','gnomADe_global_observed_alt_frequency':.00001642,'gnomADg_global_observed_alt_frequency':.00004602,'interpretation':'Existing VUS, not established somatic or actionable.'},'corrections':['Scope 21 MANE Select plus NTRK3 APPRIS principal_1','FGFR1 first-difference S134D removed; source D133dup preserved as in-frame poly-Asp insertion','ROS1 isoform-dependent protein numbering explicitly distinguished','No RNA absence inference for POLE unassessable windows','ALK earlier primary-pipeline recount not mislabeled as independent second implementation'],'source_sha256':{f:hashlib.sha256((B/f).read_bytes()).hexdigest() for f in files}}
(B/'audit.json').write_text(json.dumps(j,indent=2)+'\n')
print(json.dumps(j,indent=2))
